--using firstdatabase
use Firstdatabase

--viewing table trainers
select*from trainers

--1. Create a DML trigger to restrict DML operations on Saturday and Sunday.


--creating trigger Restrict_DML_ON_INSERT
CREATE TRIGGER Restrict_DML_ON_INSERT
ON trainers
FOR INSERT, UPDATE, DELETE
AS
BEGIN
  IF DATEPART(DW,GETDATE())= 7 or DATEPART(DW,GETDATE())= 1
  BEGIN
    PRINT 'DML OPERATIONS ARE RESTRICTED ON SATURDAY AND SUNDAY'
    ROLLBACK TRANSACTION
  END
END

INSERT INTO Trainers (TRAINEE_ID,FIRST_NAME,LAST_NAME,SALARY) VALUES (1,'SHA','D',2300)

--2. Create a DML trigger to restrict delete operations between 11:00AM to 15:00PM.

ALTER TRIGGER DML_RESTRICT_TIME
ON TRAINERS
FOR INSERT, UPDATE, DELETE
AS
BEGIN
  IF DATEPART(HH,GETDATE()) > 11 and  DATEPART(HH,GETDATE()) < 15
  BEGIN
    PRINT 'CANNOT PERFORM DML COMMANDS BETWEEN 11TH HOUR AND 15TH HOUR'
    ROLLBACK TRANSACTION
  END 
END



INSERT INTO Trainers (TRAINEE_ID,FIRST_NAME,LAST_NAME,SALARY) VALUES (10,'SHA','D',2300)


--3. Create a DDL trigger to show notification whenever a CREATE, ALTER, DROP, RENAME operation is performed.


CREATE TRIGGER SOMETHING_HAPPENED
ON DATABASE
FOR CREATE_TABLE, ALTER_TABLE,  DROP_TABLE, RENAME
AS
BEGIN
    PRINT 'YOU PERFORMED A CREATE OR ALTER OR DROP OR RENAME  STATEMENT ON THE DATABASE';
END

CREATE TABLE SHA(SHA_ID INT) --IF WE TRY TO PERFORM ANY DDL OPERATIONS THE ABOVE PRINT STATEMENT WILL BE PERFORMED

DROP TABLE SHA

DROP TRIGGER SOMETHING_HAPPENED ON DATABASE